// ============================================================================
// Kalta – P2P Sync screen
// Two-phase commit: both peers exchange bundles, each previews what would
// change locally, both must explicitly Accept before either side writes
// anything to its local DB. Either side can Reject to cancel the exchange.
//
// Hermes has a known HBC codegen bug where a static `module.member`
// reference inside a useCallback body can crash the screen on mount in
// release builds. We resolve the native module lazily via dynamic import
// so the reference isn't in the generated bytecode of any hook body.
// ============================================================================
import { useCallback, useEffect, useRef, useState } from 'react';
import {
  ActivityIndicator,
  Alert,
  FlatList,
  Pressable,
  StyleSheet,
  Text,
  View,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import * as Haptics from 'expo-haptics';
import { getActiveUser, getActiveUserId } from '@/src/lib/supabase';
import {
  decodeMessage,
  encodeMessage,
  exportSyncBundle,
  importSyncBundle,
  previewSyncBundle,
  resolutionKey,
  type P2PMessage,
  type P2PPreviewEntry,
  type P2PResolutions,
} from '@/src/lib/p2pSync';
import { colors, radius, spacing, typography } from '@/src/theme';
import { Icon } from '@/src/components/Icon';
import { ResourceIconWithOp, type ResourceTable } from '@/src/components/ResourceIcon';
import type { Category } from '@/src/types/database';

type Multipeer = typeof import('@/modules/kalta-multipeer/src');

let cachedMultipeer: Multipeer | null = null;
async function resolveMultipeer(): Promise<Multipeer> {
  if (!cachedMultipeer) {
    cachedMultipeer = await import('@/modules/kalta-multipeer/src');
  }
  return cachedMultipeer;
}

type Phase =
  | 'idle'
  | 'searching'
  | 'connecting'
  | 'connected'
  | 'exchanging'    // sent my bundle, waiting for peer's
  | 'reviewing'    // both bundles exchanged, user must accept/reject
  | 'waiting_peer' // I accepted, waiting for peer's decision
  | 'disagreed'    // both accepted but conflict picks differ
  | 'applying'     // both accepted, writing to local DB
  | 'done'
  | 'rejected'
  | 'error';

interface Peer {
  displayName: string;
}

type Decision = 'pending' | 'accept' | 'reject';

export default function P2PSyncScreen() {
  const router = useRouter();
  const [phase, setPhase] = useState<Phase>('idle');
  const [peers, setPeers] = useState<Peer[]>([]);
  const [connectedPeer, setConnectedPeer] = useState<string | null>(null);

  const [peerBundle, setPeerBundle] = useState<string | null>(null);
  const [peerSenderName, setPeerSenderName] = useState<string | null>(null);
  const [preview, setPreview] = useState<P2PPreviewEntry[]>([]);
  const [myDecision, setMyDecision] = useState<Decision>('pending');
  const [peerDecision, setPeerDecision] = useState<Decision>('pending');
  // Per-field resolutions for conflicts in this exchange. Defaults to
  // each peer's own local ("mine") value; the user can flip individual
  // fields to the peer's value before accepting. Both peers must end up
  // with the exact same map for the apply to proceed.
  const [myResolutions, setMyResolutions] = useState<P2PResolutions>({});

  const [syncResult, setSyncResult] = useState<{ inserted: number; updated: number; conflicts: number } | null>(null);
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [rejectedBy, setRejectedBy] = useState<'me' | 'peer' | null>(null);
  const userIdRef = useRef<string | null>(null);
  const userNameRef = useRef<string | null>(null);
  // Refs let event listeners read the latest values without rebinding the
  // listener every render — the multipeer event subscription is set up
  // once on mount and stays until the screen unmounts.
  const myDecisionRef = useRef<Decision>('pending');
  const peerDecisionRef = useRef<Decision>('pending');
  const peerBundleRef = useRef<string | null>(null);
  const myResolutionsRef = useRef<P2PResolutions>({});
  const peerResolutionsRef = useRef<P2PResolutions | null>(null);

  useEffect(() => { myDecisionRef.current = myDecision; }, [myDecision]);
  useEffect(() => { peerDecisionRef.current = peerDecision; }, [peerDecision]);
  useEffect(() => { peerBundleRef.current = peerBundle; }, [peerBundle]);
  useEffect(() => { myResolutionsRef.current = myResolutions; }, [myResolutions]);

  useEffect(() => {
    getActiveUserId().then((uid) => { userIdRef.current = uid; });
    getActiveUser().then((u) => { userNameRef.current = u?.email ?? null; });
  }, []);

  // Reset all sync-state when starting a fresh exchange.
  const resetExchangeState = useCallback(() => {
    setPeerBundle(null);
    setPeerSenderName(null);
    setPreview([]);
    setMyDecision('pending');
    setPeerDecision('pending');
    setMyResolutions({});
    peerResolutionsRef.current = null;
    setSyncResult(null);
    setRejectedBy(null);
  }, []);

  const handleStart = useCallback(async () => {
    try {
      const user = await getActiveUser();
      const rawName = user?.email?.trim() || 'Kalta User';
      const displayName = rawName.length > 30 ? rawName.slice(0, 30) : rawName;
      userIdRef.current = user?.id ?? null;
      userNameRef.current = user?.email ?? null;

      const mp = await resolveMultipeer();
      await mp.startSession(displayName);
      setPhase('searching');
      setPeers([]);
      setConnectedPeer(null);
      resetExchangeState();
      setErrorMsg(null);
    } catch (e: any) {
      setErrorMsg(e?.message ?? String(e) ?? 'Failed to start');
      setPhase('error');
    }
  }, [resetExchangeState]);

  // Apply the peer's bundle locally and finish. Both peers reach this
  // point only after exchanging matching resolution maps, so the import
  // is deterministic and converges both devices to the same state.
  const applyPeerBundle = useCallback(() => {
    const bundle = peerBundleRef.current;
    if (!bundle) return;
    setPhase('applying');
    try {
      const result = importSyncBundle(bundle, myResolutionsRef.current);
      setSyncResult({
        inserted: result.inserted,
        updated: result.updated,
        conflicts: result.conflicts,
      });
      setPhase('done');
      Haptics.notificationAsync(
        result.conflicts > 0
          ? Haptics.NotificationFeedbackType.Warning
          : Haptics.NotificationFeedbackType.Success,
      ).catch(() => {});
    } catch (err: any) {
      setErrorMsg(err?.message ?? 'Apply failed');
      setPhase('error');
    }
  }, []);

  useEffect(() => {
    let subs: { remove: () => void }[] = [];
    let cancelled = false;

    (async () => {
      const mp = await resolveMultipeer();
      if (cancelled) return;

      subs = [
        mp.onPeerFound((e) => {
          setPeers((prev) => {
            if (prev.some((p) => p.displayName === e.peerDisplayName)) return prev;
            return [...prev, { displayName: e.peerDisplayName }];
          });
        }),
        mp.onPeerLost((e) => {
          setPeers((prev) => prev.filter((p) => p.displayName !== e.peerDisplayName));
        }),
        mp.onConnecting((e) => {
          setPhase('connecting');
          setConnectedPeer(e.peerDisplayName);
        }),
        mp.onConnected((e) => {
          setPhase('connected');
          setConnectedPeer(e.peerDisplayName);
          Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success).catch(() => {});
        }),
        mp.onDisconnected(() => {
          // If we're mid-exchange and peer drops, treat as reject.
          if (phaseAllowsCancel()) {
            setRejectedBy('peer');
            setPhase('rejected');
          } else {
            setPhase('searching');
            setConnectedPeer(null);
            resetExchangeState();
          }
        }),
        mp.onDataReceived((e) => {
          const msg = decodeMessage(e.data);
          if (!msg) {
            setErrorMsg('Received malformed P2P message');
            setPhase('error');
            return;
          }
          handleIncomingMessage(msg);
        }),
        mp.onError((e) => {
          setErrorMsg(e.message);
          setPhase('error');
        }),
      ];
    })();

    return () => {
      cancelled = true;
      subs.forEach((s) => s.remove());
    };
    // We intentionally bind once on mount — the listeners read latest state
    // via refs and setState calls.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Handle a P2P message that just arrived from the peer.
  const handleIncomingMessage = useCallback((msg: P2PMessage) => {
    if (msg.type === 'BUNDLE') {
      // Peer sent their bundle. Compute preview and move to review.
      // Pre-populate `myResolutions` with each conflict's local value so
      // the picker has a sensible default — accepting without changing
      // anything keeps the user's own edits.
      const bundle = msg.bundle;
      try {
        const computed = previewSyncBundle(bundle);
        const defaults: P2PResolutions = {};
        for (const e of computed) {
          for (const f of e.conflict_fields) {
            const key = resolutionKey(e.table_name, e.row_id, f);
            defaults[key] = e.before_values?.[f] ?? null;
          }
        }
        setPeerBundle(bundle);
        setPeerSenderName(msg.senderName ?? null);
        setPreview(computed);
        setMyResolutions(defaults);
        setPhase('reviewing');
      } catch (err: any) {
        setErrorMsg(err?.message ?? 'Could not parse peer bundle');
        setPhase('error');
      }
      return;
    }

    if (msg.type === 'ACCEPT') {
      setPeerDecision('accept');
      peerResolutionsRef.current = msg.resolutions ?? {};
      // If I'm already accepted, compare resolutions. Both peers must
      // have made the same picks for each conflict before we apply.
      if (myDecisionRef.current === 'accept') {
        if (resolutionsAgree(myResolutionsRef.current, peerResolutionsRef.current)) {
          applyPeerBundle();
        } else {
          setPhase('disagreed');
        }
      }
      return;
    }

    if (msg.type === 'REJECT') {
      setPeerDecision('reject');
      setRejectedBy('peer');
      setPhase('rejected');
      return;
    }
  }, [applyPeerBundle]);

  const handleConnect = useCallback(async (peer: Peer) => {
    try {
      const mp = await resolveMultipeer();
      await mp.invitePeer(peer.displayName);
      setPhase('connecting');
      setConnectedPeer(peer.displayName);
    } catch (e: any) {
      Alert.alert('Connection failed', e?.message ?? 'Unknown error');
    }
  }, []);

  // User taps "Sync now" — we send our bundle. Either side can initiate.
  const handleStartSync = useCallback(async () => {
    if (!userIdRef.current) return;
    try {
      resetExchangeState();
      const bundle = exportSyncBundle(userIdRef.current);
      const mp = await resolveMultipeer();
      const message: P2PMessage = {
        type: 'BUNDLE',
        bundle,
        senderName: userNameRef.current ?? undefined,
      };
      await mp.sendData(encodeMessage(message));
      // If we already have peer's bundle (peer was first to tap), we can
      // jump straight to reviewing. Otherwise wait for theirs.
      if (peerBundleRef.current) {
        setPhase('reviewing');
      } else {
        setPhase('exchanging');
      }
    } catch (e: any) {
      setErrorMsg(e?.message ?? 'Send failed');
      setPhase('error');
    }
  }, [resetExchangeState]);

  const handleAccept = useCallback(async () => {
    setMyDecision('accept');
    const resolutions = myResolutionsRef.current;
    try {
      const mp = await resolveMultipeer();
      await mp.sendData(encodeMessage({ type: 'ACCEPT', resolutions }));
    } catch {
      /* peer may have disconnected; we'll detect via onDisconnected */
    }
    Haptics.selectionAsync().catch(() => {});
    if (peerDecisionRef.current === 'accept' && peerResolutionsRef.current !== null) {
      if (resolutionsAgree(resolutions, peerResolutionsRef.current)) {
        applyPeerBundle();
      } else {
        setPhase('disagreed');
      }
    } else {
      setPhase('waiting_peer');
    }
  }, [applyPeerBundle]);

  // User picks "Mine" / "Theirs" for a single conflict field.
  const handlePickResolution = useCallback((key: string, value: unknown) => {
    setMyResolutions((prev) => ({ ...prev, [key]: value }));
    Haptics.selectionAsync().catch(() => {});
  }, []);

  // After a disagreement, both peers reset their decision and re-enter
  // reviewing so they can adjust picks. The peer reaches the same state
  // independently because the comparison is deterministic.
  const handleAdjustPicks = useCallback(() => {
    setMyDecision('pending');
    setPeerDecision('pending');
    peerResolutionsRef.current = null;
    setPhase('reviewing');
  }, []);

  const handleReject = useCallback(async () => {
    setMyDecision('reject');
    setRejectedBy('me');
    try {
      const mp = await resolveMultipeer();
      await mp.sendData(encodeMessage({ type: 'REJECT' }));
    } catch {
      /* ignore */
    }
    Haptics.notificationAsync(Haptics.NotificationFeedbackType.Warning).catch(() => {});
    setPhase('rejected');
  }, []);

  const handleRetry = useCallback(() => {
    resetExchangeState();
    setPhase('connected');
  }, [resetExchangeState]);

  // Clean up the session on unmount.
  useEffect(() => {
    return () => {
      resolveMultipeer().then((mp) => mp.stopSession()).catch(() => {});
    };
  }, []);

  const handleDone = useCallback(() => {
    resolveMultipeer().then((mp) => mp.stopSession()).catch(() => {});
    router.back();
  }, [router]);

  const handleBack = useCallback(() => {
    resolveMultipeer().then((mp) => mp.stopSession()).catch(() => {});
    router.back();
  }, [router]);

  const peerLabel = peerSenderName ?? connectedPeer ?? 'peer';

  return (
    <SafeAreaView style={styles.container} edges={['top', 'bottom']}>
      <View style={styles.topBar}>
        <Pressable
          hitSlop={12}
          onPress={handleBack}
          style={({ pressed }) => [styles.topBarBtn, pressed && { opacity: 0.5 }]}
        >
          <Icon sf="chevron.left" size={22} color={colors.text} />
        </Pressable>
        <Text style={styles.topBarTitle}>P2P Sync</Text>
        <View style={styles.topBarBtn} />
      </View>

      {phase === 'idle' && (
        <View style={styles.center}>
          <Icon sf="antenna.radiowaves.left.and.right" size={64} color={colors.primary} />
          <Text style={styles.headline}>Sync with nearby iPhone</Text>
          <Text style={styles.description}>
            Uses Bluetooth and WiFi to exchange data directly with another Kalta device. No
            internet needed.
          </Text>
          <Pressable
            style={({ pressed }) => [styles.primaryBtn, pressed && { opacity: 0.8 }]}
            onPress={handleStart}
          >
            <Icon sf="magnifyingglass" size={18} color={colors.textOnPrimary} />
            <Text style={styles.primaryBtnText}>Start searching</Text>
          </Pressable>
        </View>
      )}

      {phase === 'searching' && (
        <View style={styles.searchSection}>
          <View style={styles.searchingHeader}>
            <ActivityIndicator color={colors.primary} />
            <Text style={styles.searchingText}>Searching for nearby devices...</Text>
          </View>
          <Text style={styles.hint}>
            Make sure the other device also has Kalta open on this screen.
          </Text>
          {peers.length > 0 && (
            <View style={styles.peerList}>
              <Text style={styles.sectionLabel}>DEVICES FOUND</Text>
              {peers.map((peer) => (
                <Pressable
                  key={peer.displayName}
                  style={({ pressed }) => [styles.peerRow, pressed && { opacity: 0.7 }]}
                  onPress={() => handleConnect(peer)}
                >
                  <Icon sf="iphone" size={24} color={colors.primary} />
                  <View style={styles.peerInfo}>
                    <Text style={styles.peerName}>{peer.displayName}</Text>
                    <Text style={styles.peerHint}>Tap to connect</Text>
                  </View>
                  <Icon sf="arrow.right.circle.fill" size={24} color={colors.primary} />
                </Pressable>
              ))}
            </View>
          )}
        </View>
      )}

      {phase === 'connecting' && (
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.headline}>Connecting...</Text>
          <Text style={styles.description}>Establishing secure connection with {peerLabel}</Text>
        </View>
      )}

      {phase === 'connected' && (
        <View style={styles.center}>
          <Icon sf="checkmark.circle.fill" size={64} color={colors.success} />
          <Text style={styles.headline}>Connected</Text>
          <Text style={styles.description}>
            Connected to {peerLabel}. Tap sync to exchange data — both of you will be able to
            review the proposed changes before anything is saved.
          </Text>
          <Pressable
            style={({ pressed }) => [styles.primaryBtn, pressed && { opacity: 0.8 }]}
            onPress={handleStartSync}
          >
            <Icon sf="arrow.triangle.2.circlepath" size={18} color={colors.textOnPrimary} />
            <Text style={styles.primaryBtnText}>Sync now</Text>
          </Pressable>
        </View>
      )}

      {phase === 'exchanging' && (
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.headline}>Exchanging data...</Text>
          <Text style={styles.description}>
            Waiting for {peerLabel} to send their changes.
          </Text>
        </View>
      )}

      {phase === 'reviewing' && (
        <ReviewList
          peerLabel={peerLabel}
          preview={preview}
          onAccept={handleAccept}
          onReject={handleReject}
          peerDecision={peerDecision}
          resolutions={myResolutions}
          onPickResolution={handlePickResolution}
        />
      )}

      {phase === 'waiting_peer' && (
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.headline}>Waiting for {peerLabel}…</Text>
          <Text style={styles.description}>
            You accepted. {peerLabel} still needs to confirm before changes apply on either
            device.
          </Text>
          <Pressable
            style={({ pressed }) => [styles.secondaryBtn, pressed && { opacity: 0.6 }]}
            onPress={handleReject}
          >
            <Text style={styles.secondaryBtnText}>Cancel</Text>
          </Pressable>
        </View>
      )}

      {phase === 'disagreed' && (
        <View style={styles.center}>
          <Icon sf="exclamationmark.triangle.fill" size={64} color={colors.warningText} />
          <Text style={styles.headline}>Picks don't match</Text>
          <Text style={styles.description}>
            You and {peerLabel} chose different values for one or more conflicts. Both devices
            need to land on the same picks before applying.
          </Text>
          <Pressable
            style={({ pressed }) => [styles.primaryBtn, pressed && { opacity: 0.8 }]}
            onPress={handleAdjustPicks}
          >
            <Icon sf="arrow.triangle.2.circlepath" size={18} color={colors.textOnPrimary} />
            <Text style={styles.primaryBtnText}>Adjust picks</Text>
          </Pressable>
          <Pressable
            style={({ pressed }) => [styles.secondaryBtn, pressed && { opacity: 0.6 }]}
            onPress={handleReject}
          >
            <Text style={styles.secondaryBtnText}>Cancel sync</Text>
          </Pressable>
        </View>
      )}

      {phase === 'applying' && (
        <View style={styles.center}>
          <ActivityIndicator size="large" color={colors.primary} />
          <Text style={styles.headline}>Applying changes…</Text>
        </View>
      )}

      {phase === 'done' && (
        <View style={styles.center}>
          <Icon
            sf={syncResult && syncResult.conflicts > 0 ? 'exclamationmark.triangle.fill' : 'checkmark.circle.fill'}
            size={64}
            color={syncResult && syncResult.conflicts > 0 ? colors.warningText : colors.success}
          />
          <Text style={styles.headline}>Sync complete</Text>
          {syncResult && (
            <Text style={styles.description}>
              {syncResult.inserted} new, {syncResult.updated} updated
              {syncResult.conflicts > 0 ? `, ${syncResult.conflicts} need your attention` : '.'}
            </Text>
          )}
          {syncResult && syncResult.conflicts > 0 && (
            <Pressable
              style={({ pressed }) => [styles.primaryBtn, pressed && { opacity: 0.8 }]}
              onPress={() => {
                resolveMultipeer().then((mp) => mp.stopSession()).catch(() => {});
                router.push('/conflicts' as any);
              }}
            >
              <Icon sf="arrow.up.right.square" size={18} color={colors.textOnPrimary} />
              <Text style={styles.primaryBtnText}>Resolve conflicts</Text>
            </Pressable>
          )}
          <Pressable
            style={({ pressed }) => [
              syncResult && syncResult.conflicts > 0 ? styles.secondaryBtn : styles.primaryBtn,
              pressed && { opacity: 0.8 },
            ]}
            onPress={handleDone}
          >
            <Text
              style={
                syncResult && syncResult.conflicts > 0
                  ? styles.secondaryBtnText
                  : styles.primaryBtnText
              }
            >
              Done
            </Text>
          </Pressable>
        </View>
      )}

      {phase === 'rejected' && (
        <View style={styles.center}>
          <Icon sf="xmark.circle.fill" size={64} color={colors.warningText} />
          <Text style={styles.headline}>Sync canceled</Text>
          <Text style={styles.description}>
            {rejectedBy === 'me'
              ? `You rejected the changes from ${peerLabel}. Nothing was saved.`
              : `${peerLabel} canceled the sync. Nothing was saved.`}
          </Text>
          <Pressable
            style={({ pressed }) => [styles.primaryBtn, pressed && { opacity: 0.8 }]}
            onPress={handleRetry}
          >
            <Icon sf="arrow.triangle.2.circlepath" size={18} color={colors.textOnPrimary} />
            <Text style={styles.primaryBtnText}>Try again</Text>
          </Pressable>
          <Pressable
            style={({ pressed }) => [styles.secondaryBtn, pressed && { opacity: 0.6 }]}
            onPress={handleDone}
          >
            <Text style={styles.secondaryBtnText}>Done</Text>
          </Pressable>
        </View>
      )}

      {phase === 'error' && (
        <View style={styles.center}>
          <Icon sf="exclamationmark.triangle.fill" size={64} color={colors.warningText} />
          <Text style={styles.headline}>Something went wrong</Text>
          <Text style={styles.description}>{errorMsg}</Text>
          <Pressable
            style={({ pressed }) => [styles.primaryBtn, pressed && { opacity: 0.8 }]}
            onPress={handleStart}
          >
            <Text style={styles.primaryBtnText}>Try again</Text>
          </Pressable>
        </View>
      )}
    </SafeAreaView>
  );

  // Phases during which a disconnect should cancel the in-flight exchange
  // rather than just bouncing back to the searching screen.
  function phaseAllowsCancel() {
    return ['exchanging', 'reviewing', 'waiting_peer'].includes(phase);
  }
}

// ----------------------------------------------------------------------------
// Review list — renders the proposed changes from the peer's bundle.
// ----------------------------------------------------------------------------

// Compare two resolution maps for full agreement. We require identical
// key sets and identical values per key — anything missing on one side
// or differing in value blocks the apply and routes both peers to the
// "disagreed" screen so they can adjust before retrying.
function resolutionsAgree(a: P2PResolutions, b: P2PResolutions): boolean {
  const keys = new Set([...Object.keys(a), ...Object.keys(b)]);
  for (const k of keys) {
    if (!(k in a) || !(k in b)) return false;
    const av = a[k];
    const bv = b[k];
    if (av === bv) continue;
    if (av == null && bv == null) continue;
    if (String(av ?? '') === String(bv ?? '')) continue;
    return false;
  }
  return true;
}

function isResolutionValueEqual(a: unknown, b: unknown): boolean {
  if (a === b) return true;
  if (a == null && b == null) return true;
  return String(a ?? '') === String(b ?? '');
}

function ReviewList({
  peerLabel,
  preview,
  onAccept,
  onReject,
  peerDecision,
  resolutions,
  onPickResolution,
}: {
  peerLabel: string;
  preview: P2PPreviewEntry[];
  onAccept: () => void;
  onReject: () => void;
  peerDecision: Decision;
  resolutions: P2PResolutions;
  onPickResolution: (key: string, value: unknown) => void;
}) {
  const conflictCount = preview.reduce((n, e) => n + e.conflict_fields.length, 0);
  const insertCount = preview.filter((e) => e.operation === 'INSERT').length;
  const updateCount = preview.filter((e) => e.operation === 'UPDATE').length;

  return (
    <View style={styles.reviewContainer}>
      <View style={styles.reviewBanner}>
        <Icon sf="person.2.fill" size={18} color={colors.warningText} />
        <View style={{ flex: 1 }}>
          <Text style={styles.reviewBannerTitle}>Changes from {peerLabel}</Text>
          <Text style={styles.reviewBannerSubtitle}>
            {preview.length === 0
              ? 'No incoming changes — nothing to apply on this device.'
              : `${insertCount} new, ${updateCount} updates${conflictCount > 0 ? `, ${conflictCount} conflicts` : ''}`}
          </Text>
        </View>
      </View>

      {peerDecision === 'accept' && (
        <View style={styles.peerStatusBar}>
          <Icon sf="checkmark.circle.fill" size={14} color={colors.success} />
          <Text style={styles.peerStatusText}>{peerLabel} already accepted</Text>
        </View>
      )}

      {preview.length === 0 ? (
        <View style={styles.center}>
          <Text style={styles.description}>
            Tap Accept to confirm — once {peerLabel} accepts as well, both devices stay in sync.
          </Text>
        </View>
      ) : (
        <FlatList
          data={preview}
          keyExtractor={(p) => `${p.table_name}:${p.row_id}`}
          contentContainerStyle={styles.reviewList}
          renderItem={({ item }) => (
            <ReviewCard
              entry={item}
              resolutions={resolutions}
              onPickResolution={onPickResolution}
            />
          )}
        />
      )}
      {conflictCount > 0 && (
        <Text style={styles.conflictHint}>
          Pick a value for each ⚠︎ conflict — both you and {peerLabel} must land on the same
          choice for the sync to apply.
        </Text>
      )}

      <View style={styles.actionBar}>
        <Pressable
          style={({ pressed }) => [styles.rejectBtn, pressed && { opacity: 0.8 }]}
          onPress={onReject}
        >
          <Icon sf="xmark" size={16} color={colors.warningText} />
          <Text style={styles.rejectBtnText}>Reject</Text>
        </Pressable>
        <Pressable
          style={({ pressed }) => [styles.acceptBtn, pressed && { opacity: 0.85 }]}
          onPress={onAccept}
        >
          <Icon sf="checkmark" size={16} color={colors.textOnPrimary} />
          <Text style={styles.acceptBtnText}>Accept</Text>
        </Pressable>
      </View>
    </View>
  );
}

const FIELD_LABELS: Record<string, string> = {
  name: 'Name',
  quantity: 'Quantity',
  unit: 'Unit',
  expiry_date: 'Expiry',
  barcode: 'Barcode',
  image_url: 'Photo',
  category: 'Category',
  notes: 'Notes',
  opened: 'Opened',
  damaged: 'Damaged',
  pack_count: 'Pack count',
  last_verified: 'Last verified',
  box_id: 'Box',
  location: 'Location',
  typical_expiry_days: 'Typical shelf life',
  completed_at: 'Completed',
  found_count: 'Found',
  missing_count: 'Missing',
};

function prettyField(field: string): string {
  return FIELD_LABELS[field] ?? field;
}

function formatValue(field: string, value: unknown): string {
  if (value === null || value === undefined || value === '') return '—';
  if (typeof value === 'boolean') return value ? 'Yes' : 'No';
  if (field === 'image_url') return 'updated';
  if (field === 'expiry_date' || field === 'last_verified' || field === 'completed_at') {
    const ts = String(value);
    if (ts === '9999-12-31') return 'Never';
    return ts.split('T')[0]?.split(' ')[0] ?? ts;
  }
  if (typeof value === 'number') {
    return Number.isInteger(value) ? String(value) : value.toFixed(2).replace(/\.?0+$/, '');
  }
  return String(value);
}

function ReviewCard({
  entry,
  resolutions,
  onPickResolution,
}: {
  entry: P2PPreviewEntry;
  resolutions: P2PResolutions;
  onPickResolution: (key: string, value: unknown) => void;
}) {
  const fields = entry.changed_fields ?? [];
  const visible = fields.filter((f) => {
    if (!entry.before_values || !entry.after_values) return true;
    return formatValue(f, entry.before_values[f]) !== formatValue(f, entry.after_values[f]);
  });
  const isDelete = entry.operation === 'DELETE';
  const isInsert = entry.operation === 'INSERT';

  return (
    <View style={styles.reviewCard}>
      <ResourceIconWithOp
        table={entry.table_name as ResourceTable}
        category={(entry.category ?? null) as Category | null}
        operation={entry.operation}
        size={36}
      />
      <View style={styles.reviewCardBody}>
        <Text style={styles.reviewCardTitle} numberOfLines={1}>
          {entry.display_name}
        </Text>
        {entry.context && (
          <Text style={styles.reviewCardContext} numberOfLines={1}>
            {entry.context}
          </Text>
        )}
        {entry.conflict_fields.length > 0 && (
          <View style={styles.conflictBadge}>
            <Icon sf="exclamationmark.triangle.fill" size={10} color={colors.warningText} />
            <Text style={styles.conflictBadgeText}>
              {entry.conflict_fields.length} conflict{entry.conflict_fields.length > 1 ? 's' : ''}
            </Text>
          </View>
        )}
        {isDelete && (
          <Text style={styles.reviewDeleteHint}>
            Will be removed from this device too if you accept.
          </Text>
        )}
        {isInsert && (
          <Text style={styles.reviewInsertHint}>
            New on this device.
          </Text>
        )}

        {visible.length > 0 && (
          <View style={styles.diff}>
            {visible.map((f) => {
              const before = entry.before_values?.[f];
              const after = entry.after_values?.[f];
              const isConflict = entry.conflict_fields.includes(f);

              if (isConflict) {
                const key = resolutionKey(entry.table_name, entry.row_id, f);
                const chosen = key in resolutions ? resolutions[key] : before;
                const mineSelected = isResolutionValueEqual(chosen, before);
                const theirsSelected = isResolutionValueEqual(chosen, after);
                return (
                  <View key={f} style={styles.diffField}>
                    <Text style={[styles.diffFieldLabel, { color: colors.warningText }]}>
                      {prettyField(f)} ⚠︎
                    </Text>
                    <Pressable
                      onPress={() => onPickResolution(key, before)}
                      style={({ pressed }) => [
                        styles.pickRow,
                        styles.pickMine,
                        mineSelected && styles.pickRowSelectedMine,
                        pressed && { opacity: 0.7 },
                      ]}
                    >
                      <Icon
                        sf={mineSelected ? 'largecircle.fill.circle' : 'circle'}
                        size={16}
                        color={mineSelected ? colors.dangerText : colors.textSubtle}
                      />
                      <View style={styles.pickContent}>
                        <Text style={styles.pickLabel}>MINE</Text>
                        <Text style={styles.pickValue} numberOfLines={2}>
                          {formatValue(f, before)}
                        </Text>
                      </View>
                    </Pressable>
                    <Pressable
                      onPress={() => onPickResolution(key, after)}
                      style={({ pressed }) => [
                        styles.pickRow,
                        styles.pickTheirs,
                        theirsSelected && styles.pickRowSelectedTheirs,
                        pressed && { opacity: 0.7 },
                      ]}
                    >
                      <Icon
                        sf={theirsSelected ? 'largecircle.fill.circle' : 'circle'}
                        size={16}
                        color={theirsSelected ? colors.successText : colors.textSubtle}
                      />
                      <View style={styles.pickContent}>
                        <Text style={styles.pickLabel}>THEIRS</Text>
                        <Text style={styles.pickValue} numberOfLines={2}>
                          {formatValue(f, after)}
                        </Text>
                      </View>
                    </Pressable>
                  </View>
                );
              }

              return (
                <View key={f} style={styles.diffField}>
                  <Text style={styles.diffFieldLabel}>{prettyField(f)}</Text>
                  {entry.before_values && (
                    <View style={styles.diffMinus}>
                      <Text style={styles.diffMinusSign}>−</Text>
                      <Text style={styles.diffMinusText} numberOfLines={2}>
                        {formatValue(f, before)}
                      </Text>
                    </View>
                  )}
                  <View style={styles.diffPlus}>
                    <Text style={styles.diffPlusSign}>+</Text>
                    <Text style={styles.diffPlusText} numberOfLines={2}>
                      {formatValue(f, after)}
                    </Text>
                  </View>
                </View>
              );
            })}
          </View>
        )}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.background },
  topBar: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.sm, paddingVertical: spacing.sm },
  topBarBtn: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
  topBarTitle: { ...typography.headline, color: colors.text, flex: 1, textAlign: 'center' },

  center: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: spacing.md, paddingHorizontal: spacing.lg, paddingBottom: 80 },

  headline: { ...typography.title2, color: colors.text, textAlign: 'center' },
  description: { ...typography.subhead, color: colors.textMuted, textAlign: 'center', maxWidth: 300 },
  hint: { ...typography.footnote, color: colors.textSubtle, textAlign: 'center', marginTop: spacing.sm },

  primaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md + 2,
    borderRadius: radius.full,
    marginTop: spacing.md,
  },
  primaryBtnText: { ...typography.bodyStrong, color: colors.textOnPrimary },

  secondaryBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: 'transparent',
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.md + 2,
    borderRadius: radius.full,
    marginTop: spacing.xs,
  },
  secondaryBtnText: { ...typography.bodyStrong, color: colors.textMuted },

  searchSection: { flex: 1, paddingTop: spacing.xl, paddingHorizontal: spacing.lg },
  searchingHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
  searchingText: { ...typography.body, color: colors.text },

  peerList: { marginTop: spacing.xl, gap: spacing.sm },
  sectionLabel: { ...typography.caption, color: colors.textMuted, fontWeight: '700', letterSpacing: 0.5, marginBottom: spacing.xs },
  peerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    padding: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  peerInfo: { flex: 1, gap: 2 },
  peerName: { ...typography.headline, color: colors.text },
  peerHint: { ...typography.footnote, color: colors.textMuted },

  // Review screen
  reviewContainer: { flex: 1, backgroundColor: colors.background },
  reviewBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.warningBg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
  reviewBannerTitle: { ...typography.headline, color: colors.text },
  reviewBannerSubtitle: { ...typography.footnote, color: colors.textMuted, marginTop: 1 },

  peerStatusBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.xs + 2,
    backgroundColor: colors.successBg,
  },
  peerStatusText: { ...typography.footnote, color: colors.successText, fontWeight: '600' },

  reviewList: { padding: spacing.lg, gap: spacing.sm, paddingBottom: 100 },

  reviewCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing.md,
    paddingTop: spacing.md + 4,
    paddingBottom: spacing.md,
    paddingHorizontal: spacing.md,
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  reviewCardBody: { flex: 1, gap: 2 },
  reviewCardTitle: { ...typography.headline, color: colors.text },
  reviewCardContext: { ...typography.footnote, color: colors.textMuted },

  conflictBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.warningBg,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: radius.sm,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  conflictBadgeText: {
    ...typography.caption,
    color: colors.warningText,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  reviewDeleteHint: {
    ...typography.footnote,
    color: colors.warningText,
    fontStyle: 'italic',
    marginTop: 4,
  },
  reviewInsertHint: {
    ...typography.footnote,
    color: colors.successText,
    fontStyle: 'italic',
    marginTop: 4,
  },

  diff: { marginTop: 10, gap: 8 },
  diffField: { gap: 3 },
  diffFieldLabel: {
    ...typography.caption,
    color: colors.textMuted,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  diffMinus: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    backgroundColor: colors.dangerBg,
    borderRadius: radius.sm,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  diffMinusSign: {
    ...typography.footnote,
    color: colors.dangerText,
    fontFamily: 'Menlo',
    fontWeight: '700',
    width: 12,
    textAlign: 'center',
  },
  diffMinusText: { ...typography.footnote, color: colors.dangerText, flex: 1, fontWeight: '500' },
  diffPlus: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 6,
    backgroundColor: colors.successBg,
    borderRadius: radius.sm,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  diffPlusSign: {
    ...typography.footnote,
    color: colors.successText,
    fontFamily: 'Menlo',
    fontWeight: '700',
    width: 12,
    textAlign: 'center',
  },
  diffPlusText: { ...typography.footnote, color: colors.successText, flex: 1, fontWeight: '500' },

  pickRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  pickMine: { backgroundColor: colors.dangerBg },
  pickTheirs: { backgroundColor: colors.successBg },
  pickRowSelectedMine: { borderColor: colors.dangerText },
  pickRowSelectedTheirs: { borderColor: colors.successText },
  pickContent: { flex: 1, gap: 2 },
  pickLabel: {
    ...typography.caption,
    color: colors.textMuted,
    fontWeight: '700',
    letterSpacing: 0.4,
  },
  pickValue: { ...typography.footnote, color: colors.text, fontWeight: '500' },

  conflictHint: {
    ...typography.footnote,
    color: colors.textMuted,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    textAlign: 'center',
  },

  actionBar: {
    flexDirection: 'row',
    gap: spacing.sm,
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: colors.border,
    backgroundColor: colors.surface,
  },
  rejectBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.warningBg,
  },
  rejectBtnText: { ...typography.bodyStrong, color: colors.warningText },
  acceptBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    backgroundColor: colors.primary,
  },
  acceptBtnText: { ...typography.bodyStrong, color: colors.textOnPrimary },
});
